#!/bin/sh
branch=$(git rev-parse --abbrev-ref HEAD)
echo "Pulling latest changes from origin/$branch"
git pull origin $branch

# Проверяем, успешно ли выполнен git pull
if [ $? -ne 0 ]; then
  echo "Error pulling latest changes. Aborting commit."
  exit 1
fi
